name: flutter_dashboard
description: Sales Dashboard Flutter Test
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  fl_chart: ^0.66.2
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  internet_connection_checker: ^1.0.0+1
  auto_route: ^9.2.2
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  responsive_toolkit: ^0.0.6
  shimmer: ^3.0.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.3.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  iconsax_plus: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.7
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  auto_route_generator: ^9.0.0
  flutter_gen_runner: ^5.7.0

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
